### ISSUE TITLE
IndexOutOfBoundsException: Invalid index 3, size is 3

### ISSUE THREAD

**Issue by munix** [HeinrichReimer/material-intro#103]
> Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at com.heinrichreimersoftware.materialintro.slide.SlideAdapter.getSlide(SlideAdapter.java:69)
       at com.heinrichreimersoftware.materialintro.app.IntroActivity.getSlide(IntroActivity.java:897)
       at com.heinrichreimersoftware.materialintro.app.IntroActivity.canGoForward(IntroActivity.java:298)
       at com.heinrichreimersoftware.materialintro.app.IntroActivity.nextSlide(IntroActivity.java:257)
       at com.heinrichreimersoftware.materialintro.app.IntroActivity$2.onClick(IntroActivity.java:240)
       at android.view.View.performClick(View.java:4438)
       at android.view.View$PerformClick.run(View.java:18431)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5061)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
       at dalvik.system.NativeStart.main(NativeStart.java)

I have 3 "addSlide" with SimpleSlide.Builder into my IntroActivity

**Comment by HeinrichReimer** [comment]
In theory this could not happen because `IntroActivity.nextSlide()`already filters out all indices that are out of range. Maybe you should check your `NavigationPolicy` or overriden `canGoForward()` methods or update the library to the latest version.
Please keep me updated if that helps.

**Comment by joeykrim** [comment]
I'm seeing a similar IndexOutOfBoundsException issue with the onBackPressed and canGoBackward methods, which in theory should not happen as the position shouldn't exceed the number of cards added/available. I'm not able to re-produce the issue locally and didn't want to open a new issue in case this is a one-off rare scenario.

As a patch, I've added your fix from the canGoForward method (if (position >= getCount())) to the onBackPressed method to also return false for any position values higher than the index rather than pass them along to the getSlide method which throws the IndexOutOfBoundsException. The additional condition in onBackPressed now looks this: `if (position <= 0 || position >= getCount()) return false;`

Stacktrace below:
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at com.heinrichreimersoftware.materialintro.app.IntroActivity.com.heinrichreimersoftware.materialintro.slide.SlideAdapter.getSlide(SourceFile:8096)
       at com.heinrichreimersoftware.materialintro.app.IntroActivity.canGoBackward(SourceFile:455)
       at com.heinrichreimersoftware.materialintro.app.IntroActivity.previousSlide(SourceFile:410)
       at com.heinrichreimersoftware.materialintro.app.IntroActivity.onBackPressed(SourceFile:224)
       at com.joeykrim.rootcheck.WelcomeScreens.onBackPressed(SourceFile:129)
       at android.app.Activity.onKeyUp(Activity.java:2273)
       at android.view.KeyEvent.dispatch(KeyEvent.java:3232)
       at android.app.Activity.dispatchKeyEvent(Activity.java:2507)
       at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(SourceFile:543)
       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(SourceFile:53)
       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(SourceFile:315)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2178)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4409)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4376)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3941)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3995)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3964)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4075)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3972)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4132)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3941)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3995)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3964)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3972)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3941)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3995)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3964)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4108)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4268)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2201)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1848)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1839)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2178)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:138)
       at android.os.Looper.loop(Looper.java:131)
       at android.app.ActivityThread.main(ActivityThread.java:5511)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
