### ISSUE TITLE
OutOfMemoryError and Lag

### ISSUE THREAD

**Issue by Pika3323** [HeinrichReimer/material-intro#110]
I have received crash logs and reports showing the library causing OutOfMemory Errors as well as generally being fairly laggy on devices running android 5.0 and up. The code and layout for the slides is pretty much just a copy of the canteen demo, however the canteen demo runs perfectly fine on those same devices. I've tried to determine a cause for the lag and crashes but have not yet found any explanation. 
(Adding/Removing the CTA button, using colours that wouldn't require transitioning, using a separate theme for the activity).

This is the crash log I received 

    java.lang.OutOfMemoryError: Failed to allocate a 37748748 byte allocation with 16777216 free bytes and 35MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:856)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:675)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:2228)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:4211)
	at android.content.res.Resources.loadDrawable(Resources.java:4085)
	at android.content.res.Resources.getDrawable(Resources.java:2005)
	at android.content.res.Resources.getDrawable(Resources.java:1987)
	at android.support.v7.widget.ResourcesWrapper.getDrawable(Unknown Source)
	at android.content.Context.getDrawable(Context.java:464)
	at android.support.v4.content.ContextCompatApi21.getDrawable(Unknown Source)
	at android.support.v4.content.ContextCompat.getDrawable(Unknown Source)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(Unknown Source)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(Unknown Source)
	at android.support.v7.widget.AppCompatImageHelper.setImageResource(Unknown Source)
	at android.support.v7.widget.AppCompatImageView.setImageResource(Unknown Source)
	at com.heinrichreimersoftware.materialintro.b.f.onCreateView(Unknown Source)
	at android.support.v4.app.Fragment.performCreateView(Unknown Source)
	at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
	at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
	at android.support.v4.app.BackStackRecord.run(Unknown Source)
	at android.support.v4.app.FragmentManagerImpl.execSingleAction(Unknown Source)
	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(Unknown Source)
	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(Unknown Source)
	at com.heinrichreimersoftware.materialintro.view.e.finishUpdate(Unknown Source)
	at android.support.v4.view.ViewPager.populate(Unknown Source)
	at android.support.v4.view.ViewPager.populate(Unknown Source)
	at android.support.v4.view.ViewPager$3.run(Unknown Source)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
	at android.view.Choreographer.doCallbacks(Choreographer.java:695)
	at android.view.Choreographer.doFrame(Choreographer.java:628)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

A method tracer also shows that it is hanging on the `android.view.ThreadedRenderer.nSyncAndDrawFrame` method, if that helps

**Comment by Pika3323** [comment]
Turns out you shouldn't stick your images into the normal drawables folder.
Should put them in a dpi-specified folder (like drawables-nodpi)

**Comment by TheMaxCoder** [comment]
@Pika3323 Can you please explain how you resolved it?
Did you just put the images in `drawable-nodpi` or you provided separate images for all DPIs?

Thanks

**Comment by HeinrichReimer** [comment]
You should just move them in the _drawable-nodpi_ folder.
Even better if you place it in the _drawable-xxxhdpi_ folder and have the right image size in pixels so that it would have the same density specific size on all devices.

**Comment by TheMaxCoder** [comment]
@HeinrichReimer Thanks much
