### ISSUE TITLE
super.OnCreate NPE error

### ISSUE THREAD

**Issue by gau4sar** [HeinrichReimer/material-intro#122]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.heinrichreimersoftware.materialintro.view.FadeableViewPager.setAdapter(android.support.v4.view.PagerAdapter)' on a null object reference
                                                                                     at com.heinrichreimersoftware.materialintro.app.IntroActivity.findViews(IntroActivity.java:282)
                                                                                     at com.heinrichreimersoftware.materialintro.app.IntroActivity.onCreate(IntroActivity.java:174)
                                                                                     at Method) 

This is my activity 

    public class AppIntroActivity extends IntroActivity {
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);

            setFullscreen(true);

            addSlide(new SimpleSlide.Builder()
                .title(R.string.welcome_text)
                .description(R.string.description)
                .image(R.drawable.finalroadlogo)
                .background(R.color.LAPIS_LAZULI)
                .backgroundDark(R.color.btn_pressed_dark_blue)
                .build());

            addSlide(new SimpleSlide.Builder()
                .title(R.string.welcome_text)
                .description(R.string.description)
                .image(R.drawable.finalroadlogo)
                .background(R.color.LAPIS_LAZULI)
                .backgroundDark(R.color.btn_pressed_dark_blue)
                .build());
        }
    }

**Comment by HeinrichReimer** [comment]
Did you call `setContentView()` or did you overrride `R.layout.activity_intro`?

**Comment by gau4sar** [comment]
The code is as it is . I have not called setContentView() neither have i overriden R.layout.activity_intro

**Comment by gau4sar** [comment]
@HeinrichReimer did you get around to solving this issue ?

**Comment by HeinrichReimer** [comment]
The error message says that the activity can't find the `ViewPager` in the content view. There are two reasons for this:

1. Someone called `setContentView()` with another layout resource
2. Someone has overriden the library's layout resource `R.layout.activity_intro`

To help me understand the issue better please use the hierachy viewer from the android development kit and post a screenshot of the layout hierachy.

**Comment by HeinrichReimer** [comment]
FYI I can't reproduce this issue on either my phone or the emulator. Are you using any framework or stuff that hacks in your Android resources?

**Comment by HeinrichReimer** [comment]
Closing due to inactivity. Will reopen this if you provide more information on how to reproduce this issue.

**Comment by suomi35** [comment]
Heinrich, I had the same issue. The cause ended up being that I had another layout named `R.layout.activity_intro`, as you suggested about. Once I got rid of that file everything worked fine.
Perhaps you could add a more unique naming convention to the library resources, like `R.layout.hrs.activity_intro` or something...or just add a note in the README ;)
Thanks for a great library!
