### ISSUE TITLE
Android 7.0: Fatal Exception when resizing the app in split-screen mode

### ISSUE THREAD

**Issue by abhijitvalluri** [HeinrichReimer/material-intro#144]
In Android 7.0, when I use the split screen feature and resize the app panel while in the intro slides portion of my app, I crash the app upon resizing it. This happens whenever I am on the second or greater slide and not the first slide. 

It looks like the cause of the crash is at [InkPageIndicator.java:626](https://github.com/HeinrichReimer/material-intro/blob/master/library/src/main/java/com/heinrichreimersoftware/materialintro/view/InkPageIndicator.java#L626). `dotCenterX` is `null` even though `getVisibility()` returns `VISIBLE`. 

Here is the crash logcat.
> 09-25 20:11:10.278 16071-16071/com.abhijitvalluri.android.fitnotifications.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                   Process: com.abhijitvalluri.android.fitnotifications.debug, PID: 16071
                                                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.abhijitvalluri.android.fitnotifications.debug/com.abhijitvalluri.android.fitnotifications.setup.AppIntroActivity}: java.lang.NullPointerException: Attempt to read from null array
                                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                                                       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4483)
                                                                                                       at android.app.ActivityThread.-wrap19(ActivityThread.java)
                                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1466)
                                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                                                       at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to read from null array
                                                                                                       at com.heinrichreimersoftware.materialintro.view.InkPageIndicator.setSelectedPage(InkPageIndicator.java:626)
                                                                                                       at com.heinrichreimersoftware.materialintro.view.InkPageIndicator.onPageSelected(InkPageIndicator.java:221)
                                                                                                       at com.heinrichreimersoftware.materialintro.view.FadeableViewPager$OnPageChangeListenerWrapper.onPageSelected(FadeableViewPager.java:75)
                                                                                                       at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1939)
                                                                                                       at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:666)
                                                                                                       at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:632)
                                                                                                       at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:613)
                                                                                                       at com.heinrichreimersoftware.materialintro.app.IntroActivity.notifyDataSetChanged(IntroActivity.java:1319)
                                                                                                       at com.heinrichreimersoftware.materialintro.app.IntroActivity.addSlide(IntroActivity.java:1175)
                                                                                                       at com.abhijitvalluri.android.fitnotifications.setup.AppIntroActivity.addEnableNotificationAccessSlide(AppIntroActivity.java:140)
                                                                                                       at com.abhijitvalluri.android.fitnotifications.setup.AppIntroActivity.onCreate(AppIntroActivity.java:311)
                                                                                                       at android.app.Activity.performCreate(Activity.java:6664)
                                                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                                                                       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4483) 
                                                                                                       at android.app.ActivityThread.-wrap19(ActivityThread.java) 
                                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1466) 
                                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                       at android.os.Looper.loop(Looper.java:154) 
                                                                                                       at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 

I noticed that `onMeasure()` is not called until all the slides are added and so till then `calculateDotPositions` does not do anything. But when I resize the app in Android 7.0, `InkPageIndicator.setSelectedPage` is called for whatever page I am on and in there the app crashes as it tries to access `dotCenterX` which is as yet `null`

Side note: I noticed that the demo app also has weird behavior when using split screen on Android 7.0. It does not crash but after scrolling from the first slide, it completely freezes on slide 2 or above if I were to resize the app. From then on, the app is completely frozen and pressing home and relaunching app is pointless as the UI does not even render. I have to completely close the app and relaunch.

**Comment by joeykrim** [comment]
A not-so-good workaround is to surround the addSlide call with try/catch. Android throws an error in logcat due to a leaked window and restarts the activity with the updated size.
