### ISSUE TITLE
NullPointerException in onAnimationUpdate

### ISSUE THREAD

**Issue by wbervoets** [HeinrichReimer/material-intro#148]
Hello,

One of my users reported the following bug with v1.6:

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.VelocityTracker.addMovement(android.view.MotionEvent)' on a null object reference
at com.heinrichreimersoftware.materialintro.a.b$5.onAnimationUpdate(IntroActivity.java:4616)
at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1374)
at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1298)
at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1339)
at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:715)
at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:738)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:829)
at android.view.Choreographer.doCallbacks(Choreographer.java:606)
at android.view.Choreographer.doFrame(Choreographer.java:575)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:815)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6934)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

Can you take a look?
I'm using fragments for each individual step.

Wim

**Comment by HeinrichReimer** [comment]
Can you post some steps how to reproduce this bug?

**Comment by mehdihaddad** [comment]
It's when you are in fakeDrag mode:
When you scroll on the page, it does not scroll (good). But if you scroll over the circle, this triggers this error.

**Comment by HeinrichReimer** [comment]
@mehdihaddad I don't quite understand the steps to reproduce that...

**Comment by vkotovv** [comment]
I've encountered the same issue in my app (report from Google Play console).
I don't have the steps to reproduce it right now, but I think this issue should be reopened.
