### ISSUE TITLE
OutOfMemoryError in SimpleSlide onCreateView of Fragment

### ISSUE THREAD

**Issue by joeykrim** [HeinrichReimer/material-intro#161]
I'm not able to reproduce, but with a limited production release I'm seeing this happen across Samsung and Motorola devices running Android 4.0.4, 4.1.2, and 4.2.2.
I'm using the latest version of this library - v1.6. Thanks

Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:631)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:577)
       at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:463)
       at android.graphics.BitmapFactory.finishDecode(BitmapFactory.java:561)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:536)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:351)
       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:783)
       at android.content.res.Resources.loadDrawable(Resources.java:1954)
       at android.content.res.Resources.getDrawable(Resources.java:666)
       at android.support.v7.widget.ResourcesWrapper.getDrawable(SourceFile:128)
       at android.support.v7.widget.TintResources.getDrawable(SourceFile:45)
       at android.support.v4.content.ContextCompat.getDrawable(SourceFile:360)
       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(SourceFile:197)
       at android.support.v7.content.res.AppCompatResources.android.support.v7.widget.AppCompatDrawableManager.getDrawable(SourceFile:1185)
       at android.support.v7.widget.AppCompatImageHelper.setImageResource(SourceFile:69)
       at android.support.v7.widget.AppCompatImageView.setImageResource(SourceFile:78)
       at com.heinrichreimersoftware.materialintro.slide.SimpleSlide$SimpleSlideFragment.onCreateView(SourceFile:492)
       at android.support.v4.app.Fragment.performCreateView(SourceFile:2080)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1108)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1290)
       at android.support.v4.app.BackStackRecord.run(SourceFile:801)
       at android.support.v4.app.BackStackRecord.android.support.v4.app.FragmentManagerImpl.execSingleAction(SourceFile:2638)
       at android.support.v4.app.FragmentPagerAdapter.finishUpdate(SourceFile:143)
       at com.heinrichreimersoftware.materialintro.view.FadeableViewPager$PagerAdapterWrapper.finishUpdate(SourceFile:142)
       at android.support.v4.view.ViewPager.populate(SourceFile:1240)
       at android.support.v4.view.ViewPager.populate(SourceFile:1088)
       at android.support.v4.view.ViewPager$3.run(SourceFile:275)
       at android.support.v4.view.ViewPager.completeScroll(SourceFile:1997)
       at android.support.v4.view.ViewPager.onInterceptTouchEvent(SourceFile:2127)
       at com.heinrichreimersoftware.materialintro.view.SwipeBlockableViewPager.onInterceptTouchEvent(SourceFile:57)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1629)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1684)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1684)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1684)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1684)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1684)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1684)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1940)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1390)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2414)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(SourceFile:63)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1888)
       at android.view.View.dispatchPointerEvent(View.java:5736)
       at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3017)
       at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2582)
       at android.view.ViewRootImpl.processInputEvents(ViewRootImpl.java:887)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:901)
       at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2558)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4697)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by HeinrichReimer** [comment]
Seems like you are trying to load a very big bitmap drawable resource into the intro.
This is not a bug this library could fix. Try to make your drawable smaller.

**Comment by joeykrim** [comment]
I'm not clear what size you're referring to as "very big", but the largest drawable image file being loaded is ~100kB, which seems to load without issue on 100,000+ other devices. I'll continue to research how to further reduce the drawable size.
For a temporary poor patch, I'll likely try/catch and ignore the OutOfMemoryError as I'd rather show text without an image, than the current flow of crashing the app.
Thanks

**Comment by HeinrichReimer** [comment]
As the stack trace says the issue occurs directly from android system code (`Bitmap.nativeCreate()`) and is therefore not related to the library but instead to android system code or to low memory on specific phones.
