### ISSUE TITLE
ArrayIndexOutOfBound

### ISSUE THREAD

**Issue by vanlooverenkoen** [HeinrichReimer/material-intro#164]
I tried to add your libary to my app. But when I create an IntroActivity like this:

```
public class TestActivity extends IntroActivity {
    @Override
    public void onCreate(Bundle savedInstanceState, PersistableBundle persistentState) {
        super.onCreate(savedInstanceState, persistentState);
        addSlide(new SimpleSlide
                .Builder()
                .title("title")
                .description("description")
                .build());
    }
}
```
I get this error:
```
 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: be.vanlooverenkoen.midimacro.dev, PID: 24058
                                                                                  java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
                                                                                      at com.heinrichreimersoftware.materialintro.view.InkPageIndicator.setJoiningFraction(InkPageIndicator.java:686)
                                                                                      at com.heinrichreimersoftware.materialintro.view.InkPageIndicator.onPageScrolled(InkPageIndicator.java:214)
                                                                                      at com.heinrichreimersoftware.materialintro.view.FadeableViewPager$OnPageChangeListenerWrapper.onPageScrolled(FadeableViewPager.java:66)
                                                                                      at android.support.v4.view.ViewPager.dispatchOnPageScrolled(ViewPager.java:1950)
                                                                                      at android.support.v4.view.ViewPager.onPageScrolled(ViewPager.java:1924)
                                                                                      at android.support.v4.view.ViewPager.pageScrolled(ViewPager.java:1862)
                                                                                      at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:693)
                                                                                      at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1806)
                                                                                      at android.view.View.layout(View.java:17637)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                      at android.view.View.layout(View.java:17637)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                      at android.view.View.layout(View.java:17637)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                      at android.view.View.layout(View.java:17637)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                      at android.view.View.layout(View.java:17637)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                      at android.view.View.layout(View.java:17637)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                      at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
                                                                                      at android.view.View.layout(View.java:17637)
                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                      at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by meierjan** [comment]
You are overwriting the wrong `onCreate()` method. 

You do:
```
public void onCreate(Bundle savedInstanceState, PersistableBundle persistentState)
```
It should be:
```
public void onCreate(Bundle savedInstanceState)
```

**Comment by HeinrichReimer** [comment]
@meierjan Didn't even notice this 😆 
Thanks for pointing that out.
