### ISSUE TITLE
pointerIndex out of range Exception

### ISSUE THREAD

**Issue by shruti-ahuja** [heinrichreimer/material-intro#208]
Unable to understand the reason of this crash. Need help!

Fatal Exception: java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getX(MotionEvent.java:2201)
       at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2092)
       at com.heinrichreimersoftware.materialintro.view.SwipeBlockableViewPager.onInterceptTouchEvent(SwipeBlockableViewPager.java:77)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2064)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2434)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2330)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1614)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2662)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2278)
       at android.view.View.dispatchPointerEvent(View.java:8424)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4804)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4665)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4223)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4277)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4246)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4357)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4254)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4414)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4223)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4277)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4246)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4254)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4223)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6546)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6459)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6430)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6395)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6626)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:138)
       at android.os.Looper.loop(Looper.java:131)
       at android.app.ActivityThread.main(ActivityThread.java:5678)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by FIndustries** [comment]
I am also getting these exceptions but the first lines change (maybe because of Proguard):

java.lang.IllegalArgumentException: 
  at android.view.MotionEvent.nativeGetAxisValue(Native Method:0)
  at android.view.MotionEvent.getX(MotionEvent.java:2024)
  at android.support.v4.view.ViewPager.**onTouchEvent**(Unknown Source:0)
  at com.heinrichreimersoftware.materialintro.view.SwipeBlockableViewPager.**onTouchEvent**(Unknown Source:0)

**Comment by heinrichreimer** [comment]
Which library version are you using?

**Comment by FIndustries** [comment]
I'm using the latest version: 1.6.2

**Comment by shruti-ahuja** [comment]
Is this fixed?

**Comment by HSY229** [comment]
**Device**: Samsung Galaxy S8+
**Android**: 8.0.0 (7.x.x is fine)
**version**: 1.6.2

## How
Use 3 fingers to click the screen at same time.

## Log
```
Fatal Exception: java.lang.IllegalArgumentExceptionpointerIndex out of range Raw Text
--
  | android.view.MotionEvent.nativeGetAxisValue (MotionEvent.java)
  | android.view.MotionEvent.getX (MotionEvent.java:2519)
  | android.support.v4.view.ViewPager.onTouchEvent (SourceFile:2277)
  | com.heinrichreimersoftware.materialintro.view.SwipeBlockableViewPager.onTouchEvent (SourceFile:72)
  | android.view.View.dispatchTouchEvent (View.java:12534)
  | android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3153)
  | android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2829)
  | android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3159)
  | android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2844)
  | android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3159)
  | android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2844)
  | android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3159)
  | android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2844)
  | android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3159)
  | android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2844)
  | android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3159)
  | android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2844)
  | android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3159)
  | android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2844)
  | com.android.internal.policy.DecorView.superDispatchTouchEvent (DecorView.java:600)
  | com.android.internal.policy.PhoneWindow.superDispatchTouchEvent (PhoneWindow.java:1871)
  | android.app.Activity.dispatchTouchEvent (Activity.java:3384)
  | android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent (SourceFile:68)
  | com.android.internal.policy.DecorView.dispatchTouchEvent (DecorView.java:562)
  | android.view.View.dispatchPointerEvent (View.java:12782)
  | android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent (ViewRootImpl.java:5615)
  | android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:5410)
  | android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4903)
  | android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4956)
  | android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4922)
  | android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:5059)
  | android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4930)
  | android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:5116)
  | android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4903)
  | android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4956)
  | android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4922)
  | android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4930)
  | android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4903)
  | android.view.ViewRootImpl.deliverInputEvent (ViewRootImpl.java:7654)
  | android.view.ViewRootImpl.doProcessInputEvents (ViewRootImpl.java:7594)
  | android.view.ViewRootImpl.enqueueInputEvent (ViewRootImpl.java:7555)
  | android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent (ViewRootImpl.java:7765)
  | android.view.InputEventReceiver.dispatchInputEvent (InputEventReceiver.java:185)
  | android.os.MessageQueue.nativePollOnce (MessageQueue.java)
  | android.os.MessageQueue.next (MessageQueue.java:325)
  | android.os.Looper.loop (Looper.java:142)
  | android.app.ActivityThread.main (ActivityThread.java:6938)
  | java.lang.reflect.Method.invoke (Method.java)
  | com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
```

**Comment by manishpatelgt** [comment]
I got the same crash recently.

```
Fatal Exception: java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getX(MotionEvent.java:2218)
       at android.support.v4.view.ViewPager.onTouchEvent(ViewPager.java:2235)
       at com.heinrichreimersoftware.materialintro.view.SwipeBlockableViewPager.onTouchEvent(SwipeBlockableViewPager.java:72)
       at android.view.View.dispatchTouchEvent(View.java:11789)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2964)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2643)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2970)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:451)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3375)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:413)
       at android.view.View.dispatchPointerEvent(View.java:12030)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4843)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4654)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4185)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4238)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4204)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4331)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4212)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4388)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4185)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4238)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4204)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4212)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4185)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6716)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6690)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6651)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6822)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:178)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6790)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6845)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:968)
       at android.view.Choreographer.doCallbacks(Choreographer.java:780)
       at android.view.Choreographer.doFrame(Choreographer.java:709)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6600)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
```

Android OS : 8.1.0
Library version: 1.6.2
