### ISSUE TITLE
Issue in release build

### ISSUE THREAD

**Issue by sunil19822701** [heinrichreimer/material-intro#212]
I getting the following error in release build
E/AndroidRuntime: FATAL EXCEPTION: main
                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{s.s.c.drmanager2/s.s.c.drmanager2.starter.Intro_Activity}: android.view.InflateException: Binary XML file line #35: Error inflating class com.heinrichreimersoftware.materialintro.view.FadeableViewPager
                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
                                                          at android.app.ActivityThread.access$600(ActivityThread.java:130)
                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                                                          at android.os.Handler.dispatchMessage(Handler.java:99)
                                                          at android.os.Looper.loop(Looper.java:137)
                                                          at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                          at java.lang.reflect.Method.invoke(Method.java:511)
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                          at dalvik.system.NativeStart.main(Native Method)
                                                       Caused by: android.view.InflateException: Binary XML file line #35: Error inflating class com.heinrichreimersoftware.materialintro.view.FadeableViewPager
                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:596)
                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                          at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                          at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:276)
                                                          at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:261)
                                                          at com.heinrichreimersoftware.materialintro.app.IntroActivity.onCreate(IntroActivity.java:198)
                                                          at s.s.c.drmanager2.starter.Intro_Activity.onCreate(Intro_Activity.java:22)
                                                          at android.app.Activity.performCreate(Activity.java:5008)
                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                          at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                          at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                          at android.os.Looper.loop(Looper.java:137) 
                                                          at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                          at java.lang.reflect.Method.invoke(Method.java:511) 
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                          at dalvik.system.NativeStart.main(Native Method) 
                                                       Caused by: java.lang.NoSuchMethodException: <init> [class android.content.Context, interface android.util.AttributeSet]
                                                          at java.lang.Class.getConstructorOrMethod(Class.java:460)
                                                          at java.lang.Class.getConstructor(Class.java:431)
                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:561)
                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                          at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                          at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:276) 
                                                          at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:261) 
                                                          at com.heinrichreimersoftware.materialintro.app.IntroActivity.onCreate(IntroActivity.java:198) 
                                                          at s.s.c.drmanager2.starter.Intro_Activity.onCreate(Intro_Activity.java:22) 
                                                          at android.app.Activity.performCreate(Activity.java:5008) 
                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023) 
                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                          at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                          at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                          at android.os.Looper.loop(Looper.java:137) 
                                                          at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                          at java.lang.reflect.Method.invoke(Method.java:511) 
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                          at dalvik.system.NativeStart.main(Native Method) 

here is my proguard
-dontwarn com.heinrichreimersoftware.materialintro.*
-dontwarn com.heinrichreimersoftware.materialintro.**
-dontwarn com.heinrichreimersoftware.materialintro.slide.*
-dontwarn com.heinrichreimersoftware.materialintro.view.*

**Comment by sunil19822701** [comment]
Sorry...there was problem in android stuido canary  2 build after android stuido update canary 3 problem solved
