### ISSUE TITLE
Bug: ArrayIndexOutOfBoundsException when clicking skip button

### ISSUE THREAD

**Issue by Spiderbezno** [HeinrichReimer/material-intro#27]
java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
                                                                                        at com.heinrichreimersoftware.materialintro.view.InkPageIndicator.setCurrentPageImmediate(InkPageIndicator.java:232)
                                                                                        at com.heinrichreimersoftware.materialintro.view.InkPageIndicator.calculateDotPositions(InkPageIndicator.java:222)
                                                                                        at com.heinrichreimersoftware.materialintro.view.InkPageIndicator.onMeasure(InkPageIndicator.java:277)
                                                                                        at android.view.View.layout(View.java:16617)
                                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                                        at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1732)
                                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
                                                                                        at android.view.View.layout(View.java:16630)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                        at android.view.View.layout(View.java:16630)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                        at android.view.View.layout(View.java:16630)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                                        at android.view.View.layout(View.java:16630)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                        at android.view.View.layout(View.java:16630)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                                        at android.view.View.layout(View.java:16630)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                        at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                                                        at android.view.View.layout(View.java:16630)
                                                                                        at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
                                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
                                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                        at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by HeinrichReimer** [comment]
What steps are needed to reproduce this issue?

**Comment by Spiderbezno** [comment]
I have only two slides and when click En skip button o finish
What steps are needed to reproduce this issue?

---
