### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'void FadeableViewPager.setAdapter(PagerAdapter)' on a null object reference

### ISSUE THREAD

**Issue by lrbgomez** [HeinrichReimer/material-intro#40]
`                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.heinrichreimersoftware.materialintro.view.FadeableViewPager.setAdapter(android.support.v4.view.PagerAdapter)' on a null object reference
                                                                         at com.heinrichreimersoftware.materialintro.app.IntroActivity.findViews(IntroActivity.java:154)
                                                                         at com.heinrichreimersoftware.materialintro.app.IntroActivity.onCreate(IntroActivity.java:81)
                                                                         at com.rhostudiomx.yuqim.MaterialIntroActivity.onCreate(MaterialIntroActivity.java:43)
                                                                         at android.app.Activity.performCreate(Activity.java:6237)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                         at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:148) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
``

**Comment by HeinrichReimer** [comment]
It seems like you have overwritten `R.layout.activity_intro`. The library can't find the viewpager in the layout.

**Comment by lrbgomez** [comment]
Absolutely.
Once I changed my `Activity` layout filename, the exception occurs no more.

Many thanks Heinrich.

**Comment by maduro69** [comment]
@heinrichreimer  can't see a the layout for Intro Activity
