### ISSUE TITLE
Next button does not work after screen rotation

### ISSUE THREAD

**Issue by Sleeper9** [HeinrichReimer/material-intro#56]
I experienced an issue with the _Next_ button. The steps to reproduce are the following:

1. Start the Intro activity with _Previous_ and _Next_ buttons enabled
2. Rotate the screen
3. Rotate the screen back to original position
4. The Next button does not work anymore (_but the Previous does_)

The screen orientation order was portrait -> landscape -> portrait, but I'm pretty sure it is also reproducable starting from landscape.
I encountered this problem on a number of devices:

- Samsung Galaxy Ace 2 @ Android 4.4.4 and 4.1.2
- Samsung Note 3 @ Android 5.0
- Samsung S Advance @ Android 4.1.2
- Nexus 7 @ Android 6.0.1

**Comment by HeinrichReimer** [comment]
Which library version are you using?
I can't reproduce the issue on Nexus 5X (@ Android N, material-intro 1.5)

**Comment by Sleeper9** [comment]
Currently, I'm on 1.4. I see you updated to 1.5, I'll update to it and report back about this!

**Comment by Sleeper9** [comment]
Well, I can confirm that the bug does not exist in the form I describe above, but there are another problems in the 1.5.1 releas: 

1. after I rotate the screen, the Intro starts back at the first slide again (I expect it to continue at the slide the rotation happened -- maybe this should be an enchancement rather than a bug)
2. when I click/slide through the slides (again), in the end, the Finish button does not work. I can slide to the left thought, but then my app crashes, and I get this stacktrace:

```
java.lang.IndexOutOfBoundsException: Invalid index 6, size is 6   

at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.get(ArrayList.java:308)
at com.heinrichreimersoftware.materialintro.slide.SlideAdapter.getSlide(SlideAdapter.java:69)
at com.heinrichreimersoftware.materialintro.app.IntroActivity.getSlide(IntroActivity.java:756)   
at com.heinrichreimersoftware.materialintro.app.IntroActivity.updateParallax(IntroActivity.java:568)
at com.heinrichreimersoftware.materialintro.app.IntroActivity.access$700(IntroActivity.java:52)      
at com.heinrichreimersoftware.materialintro.app.IntroActivity$IntroPageChangeListener.onPageScrolld(IntroActivity.java:854)
at com.heinrichreimersoftware.materialintro.view.FadeableViewPager$OnPageChangeListenerWrapper.onPageScrolled(FadeableViewPager.java:66)

```

The latter did not appear in v1.4

**Comment by Sleeper9** [comment]
Maybe we can close this issue and track those other bugs in #58 and #59 ?

**Comment by HeinrichReimer** [comment]
Yep, we should do that.
