### ISSUE TITLE
IndexOutOfBoundsException when scrolling to the end of the intro

### ISSUE THREAD

**Issue by adrcotfas** [HeinrichReimer/material-intro#59]
Hello,

Here's another fatal exception while scrolling to the end of the intro activity. I'm using the latest 1.5.1 version.

`FATAL EXCEPTION: main
                                                                             Process: com.apps.adrcotfas.goodtime, PID: 13438
                                                                             java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3
                                                                                 at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                 at java.util.ArrayList.get(ArrayList.java:308)
                                                                                 at com.heinrichreimersoftware.materialintro.slide.SlideAdapter.getSlide(SlideAdapter.java:69)
                                                                                 at com.heinrichreimersoftware.materialintro.app.IntroActivity.getSlide(IntroActivity.java:756)
                                                                                 at com.heinrichreimersoftware.materialintro.app.IntroActivity.updateParallax(IntroActivity.java:568)
                                                                                 at com.heinrichreimersoftware.materialintro.app.IntroActivity.access$700(IntroActivity.java:52)
                                                                                 at com.heinrichreimersoftware.materialintro.app.IntroActivity$IntroPageChangeListener.onPageScrolled(IntroActivity.java:854)
                                                                                 at com.heinrichreimersoftware.materialintro.view.FadeableViewPager$OnPageChangeListenerWrapper.onPageScrolled(FadeableViewPager.java:66)`

**Comment by Sleeper9** [comment]
Yes, I also noticed this in #56
