### ISSUE TITLE
ArrayIndexOutOfBandException

### ISSUE THREAD

**Issue by mehrdaad** [HeinrichReimer/material-intro#90]
Sorry to create a new issue but I'm getting this exception and can't find a solution.  

    FATAL EXCEPTION: main
              Process: com.ashojash.android.debug, PID: 7613
              java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
              at com.heinrichreimersoftware.materialintro.view.InkPageIndicator.setJoiningFraction(InkPageIndicator.java:686)
            at com.heinrichreimersoftware.materialintro.view.InkPageIndicator.onPageScrolled(InkPageIndicator.java:214)
              #at com.heinrichreimersoftware.materialintro.view.FadeableViewPager$OnPageChangeListenerWrapper.onPageScrolled(FadeableViewPager.java:66)
              at android.support.v4.view.ViewPager.dispatchOnPageScrolled(ViewPager.java:1914)
              at android.support.v4.view.ViewPager.onPageScrolled(ViewPager.java:1888)
              at android.support.v4.view.ViewPager.pageScrolled(ViewPager.java:1826)
              at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:691)
              at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1770)
              at android.view.View.layout(View.java:16636)
              at android.view.ViewGroup.layout(ViewGroup.java:5437)
              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
              at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
              at android.view.View.layout(View.java:16636)
              at android.view.ViewGroup.layout(ViewGroup.java:5437)
              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
              at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
              at android.view.View.layout(View.java:16636)
              at android.view.ViewGroup.layout(ViewGroup.java:5437)
              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
              at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
              at android.view.View.layout(View.java:16636)
              at android.view.ViewGroup.layout(ViewGroup.
              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
              at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
              at android.view.View.layout(View.java:16636)
              at android.view.ViewGroup.layout(ViewGroup.java:5437)
              at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1735)
              at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1579)
              at android.widget.LinearLayout.onLayout(LinearLayout.java:1488)
              at android.view.View.layout(View.java:16636)
              at android.view.ViewGroup.layout(ViewGroup.java:5437)
              at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
              at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
              at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
              at android.view.View.layout(View.java:16636)
              at android.view.ViewGroup.layout(ViewGroup.java:5437)
              at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2179)
              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1939)
              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
              at android.view.Choreographer.doCallbacks(Choreographer.java:670)
              at android.view.Choreographer.doFrame(Choreographer.java:606)
              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
              at android.os.Handler.handleCallback(Handler.java:739)
              at android.os.Handler.dispatchMessage(Handler.java:95)
              at android.os.Looper.loop(Looper.java:148)
              at android.app.ActivityThread.main(ActivityThread.java:5422)
              at java.lang.reflect.Method.invoke(Native Method)
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

I've tested to add 1 or 3 slides in my activity but it didn't work.

**Comment by mehrdaad** [comment]
my bad, had over written wrong signature of onCreate.
